on:
  push:
    branches: [main, dev/**]
  pull_request:
    branches: [main]

name: tests
jobs:
  tests:
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x
    - name: Build & Test
      run: |
        dotnet build -c release --tl
        dotnet test -c release --no-build
    - uses: actions/upload-artifact@v4
      with:
        path: |
          docs
          artifacts/bin/Arinc424
          artifacts/bin/Arinc424.Docs
    runs-on: ubuntu-latest
